[tool.pyright]
include = ["server"]
exclude = ["**/node_modules",
    "**/__pycache__",
]

defineConstant = { DEBUG = true }
venv = "venv"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10.12"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "server" }
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "settings.settings.development"
# -- recommended but optional:
python_files = ["test*.py", "*test.py", "testing/python/*.py"]

[tool.isort]
profile = "black"